
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author malya
 */
public class MainForm  extends javax.swing.JFrame{

    /**
     * Creates new form MainForm
     */
    Thread t;
    int x=300,left=40,y=40;
    
    private static MainForm ref=null;
    private MainForm() 
    {
        initComponents();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        setSize((int)d.getWidth(),(int)(d.getHeight()-40));
        lblmain.requestFocus();
        if(!(rdoshowpass.isSelected()))
        {
           txtpassword.setEchoChar((char)0);   
        }
     
    }
    
    //Writing a method which will return the object of it's own class.
    
    public static MainForm getObj()
    {
        if(ref==null)
        {
            ref=new MainForm();
            return ref;
        }
        else 
            return ref;
               
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        cmdlog = new java.awt.Button();
        lblstatus = new javax.swing.JLabel();
        cmbusertype = new javax.swing.JComboBox();
        txtpassword = new javax.swing.JPasswordField();
        rdoshowpass = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblmain = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MM Computer");
        setBackground(new java.awt.Color(0, 153, 204));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 45)); // NOI18N
        jLabel2.setText("     Nurshing Home");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 170, 550, 60));

        txtusername.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        txtusername.setForeground(new java.awt.Color(204, 211, 208));
        txtusername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtusername.setText("YOUR USERNAME");
        txtusername.setAlignmentX(1.0F);
        txtusername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 216, 213), 2, true));
        txtusername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtusername.setMinimumSize(new java.awt.Dimension(1, 14));
        txtusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameFocusLost(evt);
            }
        });
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusernameKeyTyped(evt);
            }
        });
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 220, 50));

        cmdlog.setBackground(new java.awt.Color(204, 215, 208));
        cmdlog.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        cmdlog.setForeground(new java.awt.Color(255, 255, 255));
        cmdlog.setLabel("Login");
        cmdlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdlogActionPerformed(evt);
            }
        });
        getContentPane().add(cmdlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 120, 40));

        lblstatus.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblstatus.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lblstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 234, 330, 30));

        cmbusertype.setBackground(new java.awt.Color(252, 91, 16));
        cmbusertype.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        cmbusertype.setForeground(new java.awt.Color(255, 255, 255));
        cmbusertype.setMaximumRowCount(3);
        cmbusertype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "          User Type", "          Admin", "          Employee" }));
        cmbusertype.setAlignmentX(0.0F);
        cmbusertype.setAlignmentY(0.0F);
        cmbusertype.setBorder(null);
        cmbusertype.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbusertype.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        cmbusertype.setFocusable(false);
        cmbusertype.setLightWeightPopupEnabled(false);
        cmbusertype.setName(""); // NOI18N
        cmbusertype.setOpaque(false);
        cmbusertype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbusertypeActionPerformed(evt);
            }
        });
        getContentPane().add(cmbusertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 220, 50));

        txtpassword.setBackground(new java.awt.Color(0, 176, 117));
        txtpassword.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(204, 216, 220));
        txtpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpassword.setText("Password");
        txtpassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 217, 234), 2, true));
        txtpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpasswordFocusLost(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpasswordKeyTyped(evt);
            }
        });
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 220, 50));

        rdoshowpass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rdoshowpass.setToolTipText("Show");
        rdoshowpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoshowpassActionPerformed(evt);
            }
        });
        getContentPane().add(rdoshowpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 460, -1, 10));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture2.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 255), null, null));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 235, 360, 380));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomePage.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 240, 180));

        lblmain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home1.jpg"))); // NOI18N
        lblmain.setText("jLabel4");
        lblmain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblmainMouseClicked(evt);
            }
        });
        getContentPane().add(lblmain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 680));
        lblmain.getAccessibleContext().setAccessibleDescription("");
        lblmain.getAccessibleContext().setAccessibleParent(this);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoshowpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoshowpassActionPerformed
        if(rdoshowpass.isSelected())
        {
            txtpassword.setEchoChar((char)0);
            txtpassword.requestFocus();
        }
        else
        {
            txtpassword.setEchoChar('*');
            txtpassword.requestFocus();
        }
    }//GEN-LAST:event_rdoshowpassActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void cmbusertypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbusertypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbusertypeActionPerformed

    private void cmdlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdlogActionPerformed
                int i=0;
        if(cmbusertype.getSelectedItem().toString().trim().equals("Admin"))
        {
            try
            {
                Connection cn=Database.getConnection();
                String sql="select username,password from admin;";
                PreparedStatement ps=cn.prepareStatement(sql);
                ResultSet rs=ps.executeQuery();
                while(rs.next())
                {
                    String username=rs.getString(1);
                    String password=rs.getString(2);

                    if(username.equals(txtusername.getText().trim()) && password.equals(new String(txtpassword.getPassword())))
                    {
                        i=1;
                        AdminPage.getObj(txtusername.getText()).setVisible(true);
                        dispose();
                        ref=null;
                    }
                }
                if(i==0)
                {
                    lblstatus.setText(" Either USERNAME or PASSWORD is wrong");
                    txtusername.setText("");
                    txtpassword.setText("");
                    txtusername.requestFocus();
                }

                cn.close();
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        else if(cmbusertype.getSelectedItem().toString().trim().equals("Employee"))
        {
            Connection cn=null;
            PreparedStatement ps=null;
            ResultSet rs=null;
            try
            {
                cn=Database.getConnection();
                String sql="select username,password from user;";
                ps=cn.prepareStatement(sql);
                rs=ps.executeQuery();
                //rs.next();
                while(rs.next())
                {
                    String username=rs.getString(1);
                    String password=rs.getString(2);
                    // JOptionPane.showMessageDialog(this, username+","+password);
                    String usname=txtusername.getText().trim();
                    String pass=new String(txtpassword.getPassword());
                    if(username.equals(usname) && password.equals(pass))
                    {
                        i=1;
                        EmployeePage.getObj(txtusername.getText().trim()).setVisible(true);
                        dispose();
                        ref=null;
                    }
                }
                if(i==0)
                {
                    lblstatus.setText(" Either USERNAME or PASSWORD is wrong");
                    txtusername.setText("YOUR USERNAME");
                    txtpassword.setText("PASSWORD");
                    txtusername.requestFocus();
                }
                
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
            finally
            {
                try {
                    if(cn!=null)
                        cn.close();
                    if(ps!=null)
                        ps.close();
                    if(rs!=null)
                        rs.close();
                } catch (SQLException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else
        {
            lblstatus.setText("                      User Type Not Exist");
        }
    }//GEN-LAST:event_cmdlogActionPerformed

    private void txtusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyTyped
        
    }//GEN-LAST:event_txtusernameKeyTyped

    private void txtusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusGained
        if(txtusername.getText().trim().equals("YOUR USERNAME"))
        {
            txtusername.setText("");
        }
        
        
    }//GEN-LAST:event_txtusernameFocusGained

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusLost
        if(txtusername.getText().equals(""))
           txtusername.setText("YOUR USER NAME");
        
    }//GEN-LAST:event_txtusernameFocusLost

    private void txtpasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyTyped
      
        if(!(rdoshowpass.isSelected()))
        {
            txtpassword.setEchoChar('*');
        }
        else
        {
            txtpassword.setEchoChar((char)0);
        }

    }//GEN-LAST:event_txtpasswordKeyTyped

    private void txtpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusGained
        if(new String(txtpassword.getPassword()).trim().equals("Password"))
        {
            txtpassword.setText("");
        }
        else if(rdoshowpass.isSelected())
        {
            txtpassword.setEchoChar((char)0);
        }
        else
            txtpassword.setEchoChar('*');
        
    }//GEN-LAST:event_txtpasswordFocusGained

    private void txtpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpasswordFocusLost
        if(new String(txtpassword.getPassword()).equals(""))
        {
            txtpassword.setText("          Password");
            txtpassword.setEchoChar((char)0);
        }
    }//GEN-LAST:event_txtpasswordFocusLost

    private void lblmainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmainMouseClicked
        if((txtusername.getText().equals("")))
        txtusername.setText("      Your User Name");
        lblmain.requestFocus();

    }//GEN-LAST:event_lblmainMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainForm.getObj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbusertype;
    private java.awt.Button cmdlog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblmain;
    private javax.swing.JLabel lblstatus;
    private javax.swing.JRadioButton rdoshowpass;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
