


import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author malya
 */
public class MisReport extends javax.swing.JFrame {

    /**
     * Creates new form MisReport
     */
    ArrayList<ReceiptPrint> recprnt;
    private static MisReport ref;
    DefaultTableModel tableModel;
    int flag=1;
    private MisReport(String date) 
    {
        initComponents();
        recprnt=Database.fetchReceipt(date);
        paneldate.setVisible(false);
        if(recprnt.size()>0)
        {
            tableModel=(DefaultTableModel)table.getModel();
            for(int i=0;i<recprnt.size();i++)
            {
                tableModel.addRow(new Object[]{i+1, recprnt.get(i).getMname(), recprnt.get(i).getAmount(), recprnt.get(i).getDate()});
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No Record exist!!");
        }
       
    }
    
    
    private MisReport() 
    {
        initComponents();
        
        tableModel=(DefaultTableModel)table.getModel();
        
       
    }
    
    public static MisReport getObj()
    {
        if(ref==null)
        {
            ref=new MisReport();
            return ref;
        }
        else
        {
            return ref;
        }
    }
    
    public static MisReport getObj(String date)
    {
        if(ref==null)
        {
            ref=new MisReport(date);
            return ref;
        }
        else
        {
            return ref;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        paneldate = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtto = new javax.swing.JTextField();
        txtfrom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmdgo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(150, 20));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SrNo.", "Medicine Name", "Amount", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(100);
            table.getColumnModel().getColumn(0).setPreferredWidth(100);
            table.getColumnModel().getColumn(0).setMaxWidth(100);
            table.getColumnModel().getColumn(2).setMinWidth(150);
            table.getColumnModel().getColumn(2).setPreferredWidth(150);
            table.getColumnModel().getColumn(2).setMaxWidth(150);
            table.getColumnModel().getColumn(3).setMinWidth(150);
            table.getColumnModel().getColumn(3).setPreferredWidth(150);
            table.getColumnModel().getColumn(3).setMaxWidth(150);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 920, 400));

        jLabel1.setFont(new java.awt.Font("Benguiat Bk BT", 1, 24)); // NOI18N
        jLabel1.setText("      MIS Report");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 230, 40));

        jLabel6.setText("jLabel6");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 90, 916, 1));

        jLabel7.setText("jLabel7");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(947, 91, 1, 82));

        jLabel8.setText("jLabel7");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 91, 1, 82));

        paneldate.setBackground(new java.awt.Color(255, 255, 255));
        paneldate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Benguiat Bk BT", 1, 15)); // NOI18N
        jLabel2.setText("To  :");
        paneldate.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Benguiat Bk BT", 1, 15)); // NOI18N
        jLabel3.setText("From :");
        paneldate.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttoKeyTyped(evt);
            }
        });
        paneldate.add(txtto, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 8, 90, 25));

        txtfrom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtfrom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfromKeyTyped(evt);
            }
        });
        paneldate.add(txtfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 8, 90, 25));

        jLabel4.setFont(new java.awt.Font("Benguiat Bk BT", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 186, 231));
        jLabel4.setText("DDMMYYYY");
        paneldate.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 30, 70, 20));

        jLabel5.setFont(new java.awt.Font("Benguiat Bk BT", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 186, 231));
        jLabel5.setText("DDMMYYYY");
        paneldate.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 30, 70, 20));

        cmdgo.setBackground(new java.awt.Color(255, 255, 255));
        cmdgo.setFont(new java.awt.Font("Benguiat Bk BT", 1, 14)); // NOI18N
        cmdgo.setText("Go");
        cmdgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdgoActionPerformed(evt);
            }
        });
        paneldate.add(cmdgo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 8, -1, -1));

        jPanel1.add(paneldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 460, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        ref=null;
        dispose();
    }//GEN-LAST:event_formWindowClosed

    private void txtfromKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfromKeyTyped
        char ch=evt.getKeyChar();
       String text=txtfrom.getText().trim();
        if(!Character.isDigit(ch) || text.length()>=8 )
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtfromKeyTyped

    private void txttoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttoKeyTyped
       char ch=evt.getKeyChar();
       String text=txtto.getText().trim();
        if(!Character.isDigit(ch) || text.length()>=8 )
        {
            evt.consume();
        }
    }//GEN-LAST:event_txttoKeyTyped

    private void cmdgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdgoActionPerformed
            String startDate=txtfrom.getText().substring(0, 2)+"/"+txtfrom.getText().substring(2, 4)+"/"+txtfrom.getText().substring(4);
            String endDate=txtto.getText().substring(0, 2)+"/"+txtto.getText().substring(2, 4)+"/"+txtto.getText().substring(4);
            
            recprnt=Database.fetchReceipt(startDate,endDate);
            
            if(table.getRowCount()>0)
            {
                for(int i=0;i<table.getRowCount();i++)
                {
                    tableModel.removeRow(i);
                }
            }
            tableModel.removeRow(0);
          
       
        if(recprnt.size()>0)
        {
            for(int i=0;i<recprnt.size();i++)
            {
            tableModel.addRow(new Object[]{i+1, recprnt.get(i).getMname(), recprnt.get(i).getAmount(), recprnt.get(i).getDate()});
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No Record Found!!");
        }
    }//GEN-LAST:event_cmdgoActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdgo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel paneldate;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtfrom;
    private javax.swing.JTextField txtto;
    // End of variables declaration//GEN-END:variables
}
