
import com.mysql.jdbc.ResultSetMetaData;
import java.awt.Graphics;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author malya
 */
public class Receipt extends javax.swing.JFrame {

    /**
     * Creates new form Records
     */
    ArrayList<User> user=null;
    DefaultTableModel model=null;
    int rcpt=0;
    private static Receipt ref=null;
    String username;
    private Receipt(DefaultTableModel model,String username) 
    {
        initComponents();
        this.model=model;
        this.username=username;
        
        DefaultTableCellRenderer alignment=new DefaultTableCellRenderer();
        alignment.setHorizontalAlignment(SwingConstants.CENTER);
        
        table.getColumn("SrNo.").setCellRenderer(alignment);
        table.getColumn("Medicine Name").setCellRenderer(alignment);
        table.getColumn("Quantity").setCellRenderer(alignment);
        table.getColumn("Amounts").setCellRenderer(alignment);
        int j;
        double total=0;
        DefaultTableModel tableModel=(DefaultTableModel)table.getModel();
        for(int i=0;i<this.model.getRowCount();i++)
        {
            j=0;
            tableModel.addRow(new Object[]{model.getValueAt(i, j++),model.getValueAt(i, j++),model.getValueAt(i, j++),model.getValueAt(i, j++)});
            total=new Double(total)+Double.parseDouble(model.getValueAt(i, --j)+"");    
        }
        txttotal.setText(total+"");
        
       
    }
    
    //Creating new constructor to print the receipt second time.
    
    public Receipt(String mname,String str_amt,String str_quantity,double amount,String username) 
    {
        initComponents();
        this.username=username;
        
        int j=1;
        String mediname[]=mname.split(",");
        String amt[]=str_amt.split(",");
        String quantity[]=str_quantity.split(",");
        
        DefaultTableModel tableModel=(DefaultTableModel)table.getModel();
        for(int i=0;i<mediname.length;i++)
        {
            tableModel.addRow(new Object[]{new Integer(j++),new String(mediname[i]),Integer.parseInt(quantity[i]),Integer.parseInt(amt[i])});
        }
        txttotal.setText(amount+"");
        
       
    }
    //Creating the method which will return the reference of this class
    
    public static Receipt getObj(DefaultTableModel model,String username)
    {
        if(ref==null && model != null)
        {
            ref=new Receipt(model,username);
            return ref;
        }
        else
            return ref;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelprint = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblcustomer = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblrcptno = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Records");
        setLocation(new java.awt.Point(300, 10));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelprint.setBackground(new java.awt.Color(255, 255, 255));
        panelprint.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setFont(new java.awt.Font("Benguiat Bk BT", 1, 14)); // NOI18N
        table.setForeground(new java.awt.Color(51, 51, 51));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SrNo.", "Medicine Name", "Quantity", "Amounts"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setColumnSelectionAllowed(true);
        table.setGridColor(new java.awt.Color(102, 102, 102));
        table.setRowHeight(30);
        jScrollPane1.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(70);
            table.getColumnModel().getColumn(0).setPreferredWidth(70);
            table.getColumnModel().getColumn(0).setMaxWidth(70);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setMinWidth(70);
            table.getColumnModel().getColumn(2).setPreferredWidth(70);
            table.getColumnModel().getColumn(2).setMaxWidth(70);
            table.getColumnModel().getColumn(3).setMinWidth(120);
            table.getColumnModel().getColumn(3).setPreferredWidth(120);
            table.getColumnModel().getColumn(3).setMaxWidth(120);
        }
        table.getAccessibleContext().setAccessibleParent(panelprint);

        panelprint.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 500, 330));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a.png"))); // NOI18N
        panelprint.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 80, 70));

        jLabel2.setFont(new java.awt.Font("Benguiat Bk BT", 1, 30)); // NOI18N
        jLabel2.setText("Prema Nurshing Home");
        panelprint.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 350, 60));

        lblcustomer.setFont(new java.awt.Font("Benguiat Bk BT", 1, 13)); // NOI18N
        lblcustomer.setText("Amit Kumar");
        panelprint.add(lblcustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 150, 30));

        lbldate.setFont(new java.awt.Font("Benguiat Bk BT", 1, 12)); // NOI18N
        lbldate.setText("08/08/2017");
        panelprint.add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 80, 20));

        jLabel5.setFont(new java.awt.Font("Benguiat Bk BT", 1, 10)); // NOI18N
        jLabel5.setText("Email ID: amitkumar@gmail.com, MobNo: 2320084");
        panelprint.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 280, 20));

        jLabel6.setFont(new java.awt.Font("Benguiat Bk BT", 1, 16)); // NOI18N
        jLabel6.setText("Name : ");
        panelprint.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 115, -1, -1));

        jLabel7.setFont(new java.awt.Font("Benguiat Bk BT", 1, 14)); // NOI18N
        jLabel7.setText("Total :                                                                Rs.");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        panelprint.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 500, 30));

        txttotal.setFont(new java.awt.Font("Benguiat Bk BT", 1, 14)); // NOI18N
        txttotal.setAlignmentX(5.0F);
        txttotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txttotal.setSelectionColor(new java.awt.Color(204, 204, 255));
        panelprint.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 100, 30));

        jLabel8.setFont(new java.awt.Font("Benguiat Bk BT", 1, 12)); // NOI18N
        jLabel8.setText("Muhammadabad Gohna Mau, PhoneNo: 2320084,8989839");
        panelprint.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 390, 20));

        lblrcptno.setFont(new java.awt.Font("Benguiat Bk BT", 1, 12)); // NOI18N
        panelprint.add(lblrcptno, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 70, 20));

        jPanel1.add(panelprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 580, 530));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Benguiat Bk BT", 1, 18)); // NOI18N
        jButton1.setText("Print");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 0), null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 650));

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int flag=0;
        try
        {
            if(flag>=0)
            {
                Toolkit tkp=panelprint.getToolkit();
                PrintJob pjb =tkp.getPrintJob(this,null, null);
                Graphics g = pjb.getGraphics();
                panelprint.print(g);
                g.dispose();
                pjb.end();
                flag=1;
            }
        
            if(flag>=0)
            {
                String cus_name="";
                if(!(lblcustomer.getText().equals("")))
                    cus_name=lblcustomer.getText();
        
                String date=lbldate.getText();
                double total_amount=Double.parseDouble(txttotal.getText());
        
                String mname="";
                String str_amount="";
                String str_quantity="";
                
                for(int i=0;i<table.getRowCount();i++)
                {
                    mname.concat(table.getValueAt(i, 1)+"");
                    str_amount.concat(table.getValueAt(i, 3)+"");
                    str_quantity.concat(table.getValueAt(i, 2)+"");
                }
        
        
            
                Connection cn=Database.getConnection();
                String sql="insert into receipt(username,mname,total_amount,str_quantity,date,customer_name,amount) values(?,?,?,?,?)";
         
                PreparedStatement ps=cn.prepareStatement(sql);
         
                ps.setString(1, username);
                ps.setString(2, mname);
                ps.setString(3, str_amount);
                ps.setString(4, str_quantity);
                ps.setString(5, date);
                ps.setString(6, cus_name);
                ps.setDouble(7, total_amount);
            }
                
        else
            JOptionPane.showMessageDialog(this, "Some error occured");
     }
    catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        dispose();
        ref=null;
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcustomer;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblrcptno;
    private javax.swing.JPanel panelprint;
    private javax.swing.JTable table;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
