
import com.sun.org.apache.xerces.internal.impl.dtd.models.CMBinOp;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.Cursor;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
//import sun.swing.table.DefaultTableCellHeaderRenderer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author malya
 */
public class SaleItem extends javax.swing.JFrame  {

    /**
     * Creates new form Work
     */
    private static SaleItem ref=null;
    String username;
    ArrayList<Stocking> m=null;
    Set<String> keys=null;
    int srno=1;
    int down=1;
    DefaultTableModel model=null;
    private SaleItem(String name) 
    {
       
            initComponents();
            this.username=name;
                
//            DefaultTableCellRenderer centreRenderer = new DefaultTableCellRenderer();
//            centreRenderer.setHorizontalAlignment(SwingConstants.CENTER);
//           
//            tablerecord.getColumn("SrNo.").setCellRenderer(centreRenderer);
//            tablerecord.getColumn("Medicine Name").setCellRenderer(centreRenderer );
//            tablerecord.getColumn("Type").setCellRenderer(centreRenderer );
//            tablerecord.getColumn("Quantity").setCellRenderer(centreRenderer );
//            tablerecord.getColumn("Amount").setCellRenderer(centreRenderer );
            
            
            
                m=Database.getMedicine2();
//                cmbname.addItem("");
//                for(int i=0;i<rs.size();i++)
//                {
//                    cmbname.addItem(rs.get(i).getMname()+", "+rs.get(i).getCompany_name());
//                }
//                
//            } 
//            catch (Exception ex) 
//            {
//                Logger.getLogger(SaleItem.class.getName()).log(Level.SEVERE, null, ex);
//            }
        
    }
    
    //Creating a method which will return the object of its class
    
    public static SaleItem getObj(String name)
    {
        
        if(ref==null)
        {
            ref=new SaleItem(name);
            return ref;
        }
        else
            return ref;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmdbill = new javax.swing.JButton();
        cmdadditem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtquantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rdotablet = new javax.swing.JRadioButton();
        rdosyrup = new javax.swing.JRadioButton();
        rdopaste = new javax.swing.JRadioButton();
        rdopkgq = new javax.swing.JRadioButton();
        rdotabletq = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablerecord = new javax.swing.JTable();
        txtmname = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        listdata = new javax.swing.JList();
        rdocapsule = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MM COMPUTER");
        setLocation(new java.awt.Point(200, 40));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Quantity :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 80, 30));

        cmdbill.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cmdbill.setText("Get Bills");
        cmdbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdbillActionPerformed(evt);
            }
        });
        jPanel3.add(cmdbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 120, 30));

        cmdadditem.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cmdadditem.setText("Add");
        cmdadditem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdadditemActionPerformed(evt);
            }
        });
        cmdadditem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmdadditemKeyTyped(evt);
            }
        });
        jPanel3.add(cmdadditem, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 80, 30));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("Medicine Name : ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 140, 30));

        txtquantity.setFont(new java.awt.Font("Benguiat Bk BT", 1, 14)); // NOI18N
        txtquantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtquantityKeyTyped(evt);
            }
        });
        jPanel3.add(txtquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 60, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setText("Type of Medicine      : ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 35, -1, -1));

        rdotablet.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdotablet);
        rdotablet.setFont(new java.awt.Font("Benguiat Bk BT", 1, 14)); // NOI18N
        rdotablet.setSelected(true);
        rdotablet.setText("Tablet");
        rdotablet.setBorder(null);
        jPanel3.add(rdotablet, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 35, -1, -1));

        rdosyrup.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdosyrup);
        rdosyrup.setFont(new java.awt.Font("Benguiat Bk BT", 1, 14)); // NOI18N
        rdosyrup.setText("Syrup");
        rdosyrup.setBorder(null);
        jPanel3.add(rdosyrup, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 35, -1, -1));

        rdopaste.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdopaste);
        rdopaste.setFont(new java.awt.Font("Benguiat Bk BT", 1, 14)); // NOI18N
        rdopaste.setText("Paste");
        rdopaste.setBorder(null);
        jPanel3.add(rdopaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 35, -1, -1));

        rdopkgq.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rdopkgq);
        rdopkgq.setFont(new java.awt.Font("Benguiat Bk BT", 1, 12)); // NOI18N
        rdopkgq.setText("Package");
        jPanel3.add(rdopkgq, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 85, -1, -1));

        rdotabletq.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rdotabletq);
        rdotabletq.setFont(new java.awt.Font("Benguiat Bk BT", 1, 12)); // NOI18N
        rdotabletq.setSelected(true);
        rdotabletq.setText("Tablet");
        jPanel3.add(rdotabletq, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 85, -1, -1));

        tablerecord.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablerecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SrNo.", "Medicine Name", "Type", "Quantity", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablerecord.getTableHeader().setResizingAllowed(false);
        tablerecord.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablerecord);
        if (tablerecord.getColumnModel().getColumnCount() > 0) {
            tablerecord.getColumnModel().getColumn(0).setMinWidth(80);
            tablerecord.getColumnModel().getColumn(0).setPreferredWidth(80);
            tablerecord.getColumnModel().getColumn(0).setMaxWidth(80);
            tablerecord.getColumnModel().getColumn(2).setMinWidth(150);
            tablerecord.getColumnModel().getColumn(2).setPreferredWidth(150);
            tablerecord.getColumnModel().getColumn(2).setMaxWidth(150);
            tablerecord.getColumnModel().getColumn(3).setMinWidth(100);
            tablerecord.getColumnModel().getColumn(3).setPreferredWidth(100);
            tablerecord.getColumnModel().getColumn(3).setMaxWidth(100);
            tablerecord.getColumnModel().getColumn(4).setMinWidth(150);
            tablerecord.getColumnModel().getColumn(4).setPreferredWidth(150);
            tablerecord.getColumnModel().getColumn(4).setMaxWidth(150);
        }

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 760, 390));

        txtmname.setFont(new java.awt.Font("Benguiat Bk BT", 1, 16)); // NOI18N
        txtmname.setNextFocusableComponent(listdata);
        txtmname.setSelectionColor(new java.awt.Color(153, 153, 153));
        txtmname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmnameKeyTyped(evt);
            }
        });
        jPanel3.add(txtmname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 76, 220, 30));

        listdata.setFont(new java.awt.Font("Benguiat Bk BT", 1, 16)); // NOI18N
        listdata.setForeground(new java.awt.Color(51, 51, 51));
        listdata.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listdata.setNextFocusableComponent(txtquantity);
        listdata.setOpaque(false);
        listdata.setSelectionBackground(new java.awt.Color(255, 255, 255));
        listdata.setValueIsAdjusting(true);
        listdata.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                listdataFocusLost(evt);
            }
        });
        listdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listdataMouseClicked(evt);
            }
        });
        listdata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                listdataKeyTyped(evt);
            }
        });
        listdata.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listdataValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listdata);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 220, 190));

        rdocapsule.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdocapsule);
        rdocapsule.setFont(new java.awt.Font("Benguiat Bk BT", 1, 14)); // NOI18N
        rdocapsule.setText("Capsule");
        rdocapsule.setBorder(null);
        jPanel3.add(rdocapsule, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 35, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 600));

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdadditemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdadditemActionPerformed
      
        try {
            model=(DefaultTableModel)tablerecord.getModel();
            double amount=1;
            int pkgq=1;
            
            for(int i=0;i<m.size();i++)
            {
                
                String text=m.get(i).getMname()+", "+m.get(i).getCompany_name();
                
                if(text.trim().equals(txtmname.getText().trim()))
                {
                    amount=m.get(i).getMrp();
                    pkgq=m.get(i).getTotalquantity()/(m.get(i).getPkg()* m.get(i).getBox());
                    break;
                }
            }
           // JOptionPane.showMessageDialog(this, amount+"fgd");
            int quantity=Integer.parseInt(txtquantity.getText());
            if(rdotabletq.isSelected())
            {
                amount=amount*quantity;
            }
            if(rdopkgq.isSelected())
            {
                amount=amount*quantity*pkgq;
            }
           // JOptionPane.showMessageDialog(this, amount);
            
            String type=rdotablet.getText();
            if(rdosyrup.isSelected())
                type=rdosyrup.getText();
            if(rdocapsule.isSelected())
                type=rdocapsule.getText();
            if(rdopaste.isSelected())
                type=rdopaste.getText();
            
            model.addRow(new Object[]{(new Integer(srno++)),txtmname.getText(),type,txtquantity.getText(),(new Double(amount))});
        }
        
        catch (Exception ex) 
        {
            Logger.getLogger(SaleItem.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cmdadditemActionPerformed

    private void txtquantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtquantityKeyTyped
        char ch=evt.getKeyChar();
        if(!(Character.isDigit(ch)|| ch=='\b'))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtquantityKeyTyped

    private void cmdbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdbillActionPerformed
        Receipt.getObj(model,username).setVisible(true);
    }//GEN-LAST:event_cmdbillActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
        dispose();
        ref=null;
        
    }//GEN-LAST:event_formWindowClosed

    private void txtmnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmnameKeyTyped

        listdata.setVisible(true);
        try {
            char ch=evt.getKeyChar();

            String mname=txtmname.getText().trim();

            if(Character.isAlphabetic(ch)|| ch=='\b')
            {
                if((mname+ch).length()>0)
                {
                    listdata.removeAll();

                    if(ch!='\b')
                    {
                        mname=mname+ch;
                    }
                    DefaultListModel listmodel=new DefaultListModel();
                    for(int i=0;i<m.size();i++)
                    {
                        if(m.get(i).getMname().contains(mname))
                        {
                            listmodel.addElement(m.get(i).getMname()+", "+m.get(i).getCompany_name());
                        }
                    }
                    listdata.setModel(listmodel);
                }
                else
                {
                    listdata.setVisible(false);
                }
                       
            }
            else
            {
                DefaultListModel listmodel=new DefaultListModel();
                for(int i=0;i<m.size();i++)
                {
                    listmodel.addElement(m.get(i).getMname()+", "+m.get(i).getCompany_name());
                }
                listdata.setModel(listmodel);
            }
        }
        catch (Exception ex)
        {
            Logger.getLogger(SaleItem.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtmnameKeyTyped

    private void listdataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listdataFocusLost
        listdata.setVisible(false);
    }//GEN-LAST:event_listdataFocusLost

    private void listdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listdataMouseClicked
        listdata.setVisible(false);

    }//GEN-LAST:event_listdataMouseClicked

    private void listdataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listdataKeyTyped
        listdata.requestFocus();
        if(evt.getKeyCode()==40)
        {
            listdata.setSelectedIndex(++down);
            txtmname.requestFocus();
        }
        if(evt.getKeyCode()==38)
        {
            listdata.setSelectedIndex(--down);
            txtmname.requestFocus();
        }
        if(evt.getKeyChar()=='\n')
        {
            listdata.setVisible(false);
            txtquantity.requestFocus();
        }
    }//GEN-LAST:event_listdataKeyTyped

    private void listdataValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listdataValueChanged
        txtmname.setText(listdata.getSelectedValue()+"");
        down=evt.getFirstIndex();
        //listdata.setVisible(false);
    }//GEN-LAST:event_listdataValueChanged

    private void cmdadditemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdadditemKeyTyped
        if(evt.getKeyChar()=='\n')
        {
                    try {
            model=(DefaultTableModel)tablerecord.getModel();
            double amount=1;
            int pkgq=1;
            
            for(int i=0;i<m.size();i++)
            {
                
                String text=m.get(i).getMname()+", "+m.get(i).getCompany_name();
                
                if(text.trim().equals(txtmname.getText().trim()))
                {
                    amount=m.get(i).getMrp();
                    pkgq=m.get(i).getTotalquantity()/(m.get(i).getPkg()* m.get(i).getBox());
                    break;
                }
            }
           // JOptionPane.showMessageDialog(this, amount+"fgd");
            int quantity=Integer.parseInt(txtquantity.getText());
            if(rdotabletq.isSelected())
            {
                amount=amount*quantity;
            }
            if(rdopkgq.isSelected())
            {
                amount=amount*quantity*pkgq;
            }
           // JOptionPane.showMessageDialog(this, amount);
            
            String type=rdotablet.getText();
            if(rdosyrup.isSelected())
                type=rdosyrup.getText();
            if(rdopaste.isSelected())
                type=rdopaste.getText();
            
            model.addRow(new Object[]{(new Integer(srno++)),txtmname.getText(),type,txtquantity.getText(),(new Double(amount))});
        }
        
        catch (Exception ex) 
        {
            Logger.getLogger(SaleItem.class.getName()).log(Level.SEVERE, null, ex);
        }

        }
    }//GEN-LAST:event_cmdadditemKeyTyped

 /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaleItem.getObj("username").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cmdadditem;
    private javax.swing.JButton cmdbill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listdata;
    private javax.swing.JRadioButton rdocapsule;
    private javax.swing.JRadioButton rdopaste;
    private javax.swing.JRadioButton rdopkgq;
    private javax.swing.JRadioButton rdosyrup;
    private javax.swing.JRadioButton rdotablet;
    private javax.swing.JRadioButton rdotabletq;
    private javax.swing.JTable tablerecord;
    private javax.swing.JTextField txtmname;
    private javax.swing.JTextField txtquantity;
    // End of variables declaration//GEN-END:variables
}
