
//import com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author malya
 */

public class Search extends javax.swing.JFrame {

    /**
     * Creates new form Search
     */
    private  static Search ref=null;
    DefaultTableModel model=null;
    ArrayList<Stocking> m=null;
   // Set<String> keys=null;
    int flag=0;
    int box;
    int pkg;
    int tq;
    int dl;
    int selection;
    int down=1;
    private Search() 
    {
        initComponents();
        //JOptionPane.showMessageDialog(this, "hii");
      /*  DefaultTableCellRenderer alignment=new DefaultTableCellRenderer();
        alignment.setHorizontalAlignment(SwingConstants.CENTER);
        table.getColumn("Medicine Name").setCellRenderer(alignment);
        table.getColumn("Box").setCellRenderer(alignment);
        table.getColumn("Pkg / Box").setCellRenderer(alignment);
        table.getColumn("Tablet / Pkg").setCellRenderer(alignment);
        table.getColumn("DeadLine").setCellRenderer(alignment);
        table.getColumn("Cost").setCellRenderer(alignment);
        table.getColumn("MRP / Tablet").setCellRenderer(alignment);
        table.getColumn("Date").setCellRenderer(alignment);
        
*/
        model=(DefaultTableModel)table.getModel();
        m=Database.getMedicine2();

    }
    
    
    public static Search getObj()
    {
        if(ref==null)
        {
            ref=new Search();
            return ref;
        }
        else
            return ref;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        cmdsearch = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtmname = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listdata = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(255, 30));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Benguiat Bk BT", 1, 18)); // NOI18N
        jLabel1.setText("Medicine Name :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        table.setFont(new java.awt.Font("Benguiat Bk BT", 1, 14)); // NOI18N
        table.setForeground(new java.awt.Color(51, 51, 51));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Name", "Type", "Box", "Pkg / Box", "Tablet / Pkg", "DeadLine", "MRP / Tablet"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setColumnSelectionAllowed(true);
        table.setGridColor(new java.awt.Color(255, 255, 255));
        table.setRowHeight(30);
        table.setSelectionBackground(new java.awt.Color(204, 204, 204));
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(1).setMinWidth(150);
            table.getColumnModel().getColumn(1).setPreferredWidth(150);
            table.getColumnModel().getColumn(1).setMaxWidth(150);
            table.getColumnModel().getColumn(2).setMinWidth(50);
            table.getColumnModel().getColumn(2).setPreferredWidth(50);
            table.getColumnModel().getColumn(2).setMaxWidth(50);
            table.getColumnModel().getColumn(3).setMinWidth(80);
            table.getColumnModel().getColumn(3).setPreferredWidth(80);
            table.getColumnModel().getColumn(3).setMaxWidth(80);
            table.getColumnModel().getColumn(4).setMinWidth(80);
            table.getColumnModel().getColumn(4).setPreferredWidth(80);
            table.getColumnModel().getColumn(4).setMaxWidth(80);
            table.getColumnModel().getColumn(5).setMinWidth(80);
            table.getColumnModel().getColumn(5).setPreferredWidth(80);
            table.getColumnModel().getColumn(5).setMaxWidth(80);
            table.getColumnModel().getColumn(6).setMinWidth(100);
            table.getColumnModel().getColumn(6).setPreferredWidth(100);
            table.getColumnModel().getColumn(6).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 820, 140));

        cmdsearch.setFont(new java.awt.Font("Benguiat Bk BT", 1, 14)); // NOI18N
        cmdsearch.setText("Search");
        cmdsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsearchActionPerformed(evt);
            }
        });
        cmdsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmdsearchKeyTyped(evt);
            }
        });
        jPanel1.add(cmdsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 90, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ref.jpg"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, 30, 30));

        txtmname.setFont(new java.awt.Font("Benguiat Bk BT", 1, 16)); // NOI18N
        txtmname.setNextFocusableComponent(listdata);
        txtmname.setSelectionColor(new java.awt.Color(153, 153, 153));
        txtmname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmnameKeyTyped(evt);
            }
        });
        jPanel1.add(txtmname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 105, 280, 30));

        listdata.setFont(new java.awt.Font("Benguiat Bk BT", 1, 16)); // NOI18N
        listdata.setForeground(new java.awt.Color(51, 51, 51));
        listdata.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listdata.setNextFocusableComponent(txtmname);
        listdata.setOpaque(false);
        listdata.setSelectionBackground(new java.awt.Color(255, 255, 255));
        listdata.setValueIsAdjusting(true);
        listdata.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                listdataFocusLost(evt);
            }
        });
        listdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listdataMouseClicked(evt);
            }
        });
        listdata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                listdataKeyTyped(evt);
            }
        });
        listdata.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listdataValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listdata);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 280, 180));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 400));

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        dispose();
        ref=null;
    }//GEN-LAST:event_formWindowClosed

    private void cmdsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsearchActionPerformed

        if(flag==0)
        {
            try
            {
                flag=1;
                
                String text[]=(txtmname.getText()).split(",");
                for(int i=0;i<m.size();i++)
                {
                    if(text[0].equals(m.get(i).getMname()))
                    {
                        box=m.get(i).getBox();
                        pkg=m.get(i).getPkg();
                        dl=m.get(i).getDeadline();
                        tq=m.get(i).getTotalquantity();
                        int tabletp=tq/(box*pkg);
                        model.addRow(new Object[]{m.get(i).getMname(),m.get(i).getType(),
                        box,pkg,tabletp,dl,m.get(i).getMrp()});
                        table.setEditingRow(i);
                
                        break;
                    }
                }
                cmdsearch.setText("Reset");
                
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this, "Data does not exist..");
            }
        }
       else
        {
            model.removeRow(0);
            flag=0;
            cmdsearch.setText("Search");
        }
       
    }//GEN-LAST:event_cmdsearchActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        flag=0;    
        cmdsearch.setText("Search");
       
        if(model.getRowCount()>0)
            model.removeRow(0);
        listdata.removeAll();
        m=Database.getMedicine2();
        DefaultListModel listmodel=new DefaultListModel();
        String mname=txtmname.getText();
        for(int i=0;i<m.size();i++)
        {            
            if(m.get(i).getMname().contains(mname))
            {
                listmodel.addElement(m.get(i).getMname()+", "+m.get(i).getCompany_name());
            }
        }
        listdata.setModel(listmodel);
        JOptionPane.showMessageDialog(this, "Record Updated Successfully !!");
    }//GEN-LAST:event_jLabel7MouseClicked

    private void txtmnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmnameKeyTyped

        listdata.setVisible(true);
        try {
            char ch=evt.getKeyChar();
            
            String mname=txtmname.getText().trim();
            
            
            if(Character.isAlphabetic(ch)|| ch=='\b')
            {
                if((mname+ch).length()>0)
                {
                    listdata.removeAll();
                    
                    if(ch!='\b')
                    {
                        mname=mname+ch;
                    }
                    DefaultListModel listmodel=new DefaultListModel();
                    
                    for(int i=0;i<m.size();i++)
                    {            
                        if(m.get(i).getMname().contains(mname))
                        {
                    
                            listmodel.addElement(m.get(i).getMname()+", "+m.get(i).getType()+", "+m.get(i).getCompany_name());
                        }
                    }
                    
                   listdata.setModel(listmodel);
                }
                else
                {
                    listdata.setVisible(false);
                }
            }
            else
            {
                    DefaultListModel listmodel=new DefaultListModel();
                    for(int i=0;i<m.size();i++)
                    {            
                        listmodel.addElement(m.get(i).getMname()+", "+m.get(i).getType()+", "+m.get(i).getCompany_name());
                    }
                    listdata.setModel(listmodel);
            }
        }
        catch (Exception ex) 
        {
            Logger.getLogger(SaleItem.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_txtmnameKeyTyped

    private void listdataValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listdataValueChanged
        txtmname.setText(listdata.getSelectedValue()+"");
        down=evt.getFirstIndex();
        //listdata.setVisible(false);
    }//GEN-LAST:event_listdataValueChanged

    private void listdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listdataMouseClicked
        listdata.setVisible(false);
        
    }//GEN-LAST:event_listdataMouseClicked

    private void listdataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listdataKeyTyped
        listdata.requestFocus();
        if(evt.getKeyCode()==40)
        {
            listdata.setSelectedIndex(++down);
            txtmname.requestFocus();
        }
        if(evt.getKeyCode()==38)
        {
            listdata.setSelectedIndex(--down);
            txtmname.requestFocus();
        }
        if(evt.getKeyChar()=='\n')
        {
            listdata.setVisible(false);
            cmdsearch.requestFocus();
        }
    }//GEN-LAST:event_listdataKeyTyped

    private void listdataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_listdataFocusLost
//        listdata.setVisible(false);
    }//GEN-LAST:event_listdataFocusLost

    private void cmdsearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdsearchKeyTyped
    
        if(flag==0)
        {
            try
            {
                flag=1;
                
                String text[]=(txtmname.getText()).split(",");
                for(int i=0;i<m.size();i++)
                {
                    if(text[0].equals(m.get(i).getMname()))
                    {
                        box=m.get(i).getBox();
                        pkg=m.get(i).getPkg();
                        dl=m.get(i).getDeadline();
                        tq=m.get(i).getTotalquantity();
                        int tabletp=tq/(box*pkg);
                        model.addRow(new Object[]{m.get(i).getMname(),
                        box,pkg,tabletp,dl,m.get(i).getMrp()});
                        table.setEditingRow(i);
                
                        break;
                    }
                }
                cmdsearch.setText("Reset");
                
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this, "Data does not exist..");
            }
        }
       else
        {
            model.removeRow(0);
            flag=0;
            cmdsearch.setText("Search");
        }
    }//GEN-LAST:event_cmdsearchKeyTyped

    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listdata;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtmname;
    // End of variables declaration//GEN-END:variables


}
