
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Set;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author malya
 */
public class Stock extends javax.swing.JFrame {

    /**
     * Creates new form Work
     */
    String username;
    private static Stock ref=null;
    public Stock(String name)
    {
        initComponents();
        this.username=name;
    }
    
    //Creating a method which will return of this class.
    
    public static Stock getObj(String name)
    {
        if(ref==null)
        {
            ref=new Stock(name);
            return ref;
        }
        else
            return ref;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtmname = new javax.swing.JTextField();
        txtmrp = new javax.swing.JTextField();
        txtcost = new javax.swing.JTextField();
        txtsname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtsmobile = new javax.swing.JTextField();
        txtpkg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtdeadline = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtbox = new javax.swing.JTextField();
        txttablets = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rdotablet = new javax.swing.JRadioButton();
        rdosyrup = new javax.swing.JRadioButton();
        rdopaste = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtcompany = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        rdocapsule = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Medicine Details");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(302, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Benguiat Bk BT", 1, 18)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 140, 35));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setText("M.R.P.                      :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));
        jLabel3.getAccessibleContext().setAccessibleParent(jPanel2);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Date                     :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 473, -1, 20));
        jLabel5.getAccessibleContext().setAccessibleParent(jPanel2);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("DDMMYYYY");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 82, 28));
        jLabel6.getAccessibleContext().setAccessibleParent(jPanel2);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 204));
        jLabel2.setText("(MRP / Tablet)");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 377, -1, -1));
        jLabel2.getAccessibleContext().setAccessibleParent(jPanel2);

        txtdate.setBackground(new java.awt.Color(204, 222, 230));
        txtdate.setFont(new java.awt.Font("Benguiat Bk BT", 1, 15)); // NOI18N
        txtdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdateFocusLost(evt);
            }
        });
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });
        txtdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdateKeyTyped(evt);
            }
        });
        jPanel2.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 110, 30));
        txtdate.getAccessibleContext().setAccessibleParent(jPanel2);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setText("Medicine Name        :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 173, 150, -1));
        jLabel1.getAccessibleContext().setAccessibleParent(jPanel2);

        txtmname.setBackground(new java.awt.Color(204, 222, 230));
        txtmname.setFont(new java.awt.Font("Benguiat Bk BT", 1, 15)); // NOI18N
        txtmname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmnameActionPerformed(evt);
            }
        });
        txtmname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmnameKeyTyped(evt);
            }
        });
        jPanel2.add(txtmname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 200, 30));
        txtmname.getAccessibleContext().setAccessibleParent(jPanel2);

        txtmrp.setBackground(new java.awt.Color(204, 222, 230));
        txtmrp.setFont(new java.awt.Font("Benguiat Bk BT", 1, 15)); // NOI18N
        txtmrp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmrp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmrpKeyTyped(evt);
            }
        });
        jPanel2.add(txtmrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 110, 30));
        txtmrp.getAccessibleContext().setAccessibleParent(jPanel2);

        txtcost.setBackground(new java.awt.Color(204, 222, 230));
        txtcost.setFont(new java.awt.Font("Benguiat Bk BT", 1, 15)); // NOI18N
        txtcost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcostActionPerformed(evt);
            }
        });
        txtcost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcostKeyTyped(evt);
            }
        });
        jPanel2.add(txtcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 200, 30));
        txtcost.getAccessibleContext().setAccessibleParent(jPanel2);

        txtsname.setBackground(new java.awt.Color(204, 222, 230));
        txtsname.setFont(new java.awt.Font("Benguiat Bk BT", 1, 15)); // NOI18N
        txtsname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsnameActionPerformed(evt);
            }
        });
        txtsname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsnameKeyTyped(evt);
            }
        });
        jPanel2.add(txtsname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 200, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel4.setText("Type of Medicine      : ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("MobNo(Supplier)      : ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 122, 150, 20));

        txtsmobile.setBackground(new java.awt.Color(204, 222, 230));
        txtsmobile.setFont(new java.awt.Font("Benguiat Bk BT", 1, 15)); // NOI18N
        txtsmobile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsmobile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsmobileFocusLost(evt);
            }
        });
        txtsmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsmobileActionPerformed(evt);
            }
        });
        txtsmobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsmobileKeyTyped(evt);
            }
        });
        jPanel2.add(txtsmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 200, 30));

        txtpkg.setBackground(new java.awt.Color(204, 222, 230));
        txtpkg.setFont(new java.awt.Font("Benguiat Bk BT", 1, 15)); // NOI18N
        txtpkg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpkg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpkgActionPerformed(evt);
            }
        });
        txtpkg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpkgKeyTyped(evt);
            }
        });
        jPanel2.add(txtpkg, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 50, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("Quantity                    :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 316, -1, -1));

        txtdeadline.setBackground(new java.awt.Color(204, 222, 230));
        txtdeadline.setFont(new java.awt.Font("Benguiat Bk BT", 1, 15)); // NOI18N
        txtdeadline.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdeadlineActionPerformed(evt);
            }
        });
        txtdeadline.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdeadlineKeyTyped(evt);
            }
        });
        jPanel2.add(txtdeadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 110, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setText("DeadLine                  :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 423, -1, -1));

        txtbox.setBackground(new java.awt.Color(204, 222, 230));
        txtbox.setFont(new java.awt.Font("Benguiat Bk BT", 1, 15)); // NOI18N
        txtbox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtboxActionPerformed(evt);
            }
        });
        txtbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtboxKeyTyped(evt);
            }
        });
        jPanel2.add(txtbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 50, 30));

        txttablets.setBackground(new java.awt.Color(204, 222, 230));
        txttablets.setFont(new java.awt.Font("Benguiat Bk BT", 1, 15)); // NOI18N
        txttablets.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttabletsActionPerformed(evt);
            }
        });
        txttablets.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttabletsKeyTyped(evt);
            }
        });
        jPanel2.add(txttablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 60, 30));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setText("Cost                           :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 274, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 204));
        jLabel11.setText("(No of Boxes)");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 425, 80, 20));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 204));
        jLabel13.setText("(No of Box)");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 60, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel14.setText("Supplier Name           : ");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 72, -1, -1));

        rdotablet.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdotablet);
        rdotablet.setFont(new java.awt.Font("Benguiat Bk BT", 1, 14)); // NOI18N
        rdotablet.setSelected(true);
        rdotablet.setText("Tablet");
        rdotablet.setBorder(null);
        jPanel2.add(rdotablet, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        rdosyrup.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdosyrup);
        rdosyrup.setFont(new java.awt.Font("Benguiat Bk BT", 1, 14)); // NOI18N
        rdosyrup.setText("Syrup");
        rdosyrup.setBorder(null);
        jPanel2.add(rdosyrup, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        rdopaste.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdopaste);
        rdopaste.setFont(new java.awt.Font("Benguiat Bk BT", 1, 14)); // NOI18N
        rdopaste.setText("Paste");
        rdopaste.setBorder(null);
        jPanel2.add(rdopaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 204, 51));
        jLabel15.setText("(Pkg / Box)");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 204));
        jLabel16.setText("(Tablets / pkg)");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, -1));

        txtcompany.setBackground(new java.awt.Color(204, 222, 230));
        txtcompany.setFont(new java.awt.Font("Benguiat Bk BT", 1, 15)); // NOI18N
        txtcompany.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcompanyActionPerformed(evt);
            }
        });
        txtcompany.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcompanyKeyTyped(evt);
            }
        });
        jPanel2.add(txtcompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 200, 30));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel12.setText("Company Name        :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 223, 150, -1));

        rdocapsule.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdocapsule);
        rdocapsule.setFont(new java.awt.Font("Benguiat Bk BT", 1, 14)); // NOI18N
        rdocapsule.setText("Capsule");
        rdocapsule.setBorder(null);
        jPanel2.add(rdocapsule, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 610));

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            
            //Code to add medicine details in the database.
            Connection cn=Database.getConnection();
            String sql="insert into medicine(mname,company_name,cost,mrp,deadline,box,package,totalquantity,date,type) values(?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps=cn.prepareStatement(sql);
            
            ps.setString(1, txtmname.getText().toUpperCase());
            ps.setString(2, txtcompany.getText().toUpperCase());
            ps.setDouble(3, Double.parseDouble(txtcost.getText()));
            ps.setDouble(4, Double.parseDouble(txtmrp.getText()));
            ps.setInt(5, Integer.parseInt(txtdeadline.getText()));
            
            //Calculating for total medicine.
            int box=Integer.parseInt(txtbox.getText().toUpperCase());
            int pkg=Integer.parseInt(txtpkg.getText().toUpperCase());
            int totalq=Integer.parseInt(txttablets.getText());
            int total=box*pkg*totalq;
            
            ps.setInt(6, box);
            ps.setInt(7, pkg);
            ps.setInt(8, total);
            
            String date=txtdate.getText();
            date=date.substring(0, 2)+"/"+date.substring(2, 4)+"/"+date.substring(4, 8);
            ps.setString(9, date);
            
            String type=rdotablet.getText().toUpperCase();
//            JOptionPane.showMessageDialog(this, type);
            if(rdosyrup.isSelected())
                type=rdosyrup.getText().toUpperCase();
            if(rdocapsule.isSelected())
                type=rdocapsule.getText().toUpperCase();
            if(rdopaste.isSelected())
                type=rdopaste.getText().toUpperCase();
            
            
            ps.setString(10, type);
            ps.executeUpdate();
          
            //code to check the supplier exists or not
            
           ArrayList<SuppliersDetails> keys=Database.fetchSuppliers();
            int check=0;
            for(SuppliersDetails val:keys)
            {
                
                if(val.getName().equals(txtsname.getText()))
                {
                    check=1;
                    break;
                }
            }
            
            if(check==0)
            {
            
                //Connection cn=Database.getConnection();
                String sql1="insert into suppliers(name,mobileNo) values(?,?)";
                PreparedStatement ps1=cn.prepareStatement(sql1);
                ps1.setString(1, txtsname.getText());
                ps1.setString(2, txtsmobile.getText());
                ps1.executeUpdate();
            }
            
            
            JOptionPane.showMessageDialog(this, "Medicine Stocked Successfully !!");
            txtmname.setText("");
            txtcost.setText("");
            txtmrp.setText("");
            txtdeadline.setText("");
            txtbox.setText("");
            txtpkg.setText("");
            txttablets.setText("");
            
            txtmname.requestFocus();
            cn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcostKeyTyped
        char ch=evt.getKeyChar();
        if(!((Character.isDigit(ch)) || ch=='.' ||ch=='\b'))
        {
            evt.consume();
        }

    }//GEN-LAST:event_txtcostKeyTyped

    private void txtcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcostActionPerformed

    private void txtmrpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmrpKeyTyped
        char ch=evt.getKeyChar();
        if(!((Character.isDigit(ch)) || ch=='.' ||ch=='\b'))
        {
            evt.consume();
        }

    }//GEN-LAST:event_txtmrpKeyTyped

    private void txtmnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmnameKeyTyped
        char ch=evt.getKeyChar();
        if(!(Character.isAlphabetic(ch))&& ch!=' ')
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtmnameKeyTyped

    private void txtmnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmnameActionPerformed

    private void txtdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdateKeyTyped
        char ch=evt.getKeyChar();
        String text=txtdate.getText().trim();
        if(!Character.isDigit(ch) || text.length()>=8 )
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtdateKeyTyped

    private void txtdateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdateFocusLost
        if(txtdate.getText().trim().length()!=8)
        {
            JOptionPane.showMessageDialog(this, "Enter Correct Date.","Error",JOptionPane.ERROR_MESSAGE);
            txtdate.requestFocus();
        }
    }//GEN-LAST:event_txtdateFocusLost

    private void txtsnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsnameActionPerformed

    private void txtsnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsnameKeyTyped
        char ch=evt.getKeyChar();
        if(!(Character.isAlphabetic(ch))&& ch!=' ')
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtsnameKeyTyped

    private void txtsmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsmobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsmobileActionPerformed

    private void txtsmobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsmobileKeyTyped
        char ch=evt.getKeyChar();
        String text=txtsmobile.getText().trim();
        if(!(Character.isDigit(ch)) || text.length()>=10)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtsmobileKeyTyped

    private void txtpkgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpkgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpkgActionPerformed

    private void txtpkgKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpkgKeyTyped
        char ch=evt.getKeyChar();
        if(!Character.isDigit(ch))
        {
            evt.consume();
        }

    }//GEN-LAST:event_txtpkgKeyTyped

    private void txtdeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdeadlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdeadlineActionPerformed

    private void txtdeadlineKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdeadlineKeyTyped
        char ch=evt.getKeyChar();
//        String text=txtdeadline.getText().trim();
        if(!Character.isDigit(ch))
        {
            evt.consume();
        }

    }//GEN-LAST:event_txtdeadlineKeyTyped

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void txtboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtboxActionPerformed

    private void txtboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtboxKeyTyped
        char ch=evt.getKeyChar();

        if(!Character.isDigit(ch))
        {
            evt.consume();
        }

    }//GEN-LAST:event_txtboxKeyTyped

    private void txttabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttabletsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttabletsActionPerformed

    private void txttabletsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttabletsKeyTyped
        char ch=evt.getKeyChar();
        if(!Character.isDigit(ch))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txttabletsKeyTyped

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       dispose();
       ref=null;
    }//GEN-LAST:event_formWindowClosed

    private void txtcompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcompanyActionPerformed

    private void txtcompanyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcompanyKeyTyped
       char ch=evt.getKeyChar();
        if(!(Character.isAlphabetic(ch))&& ch!=' ')
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtcompanyKeyTyped

    private void txtsmobileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsmobileFocusLost
        if(txtsmobile.getText().length()<10 && txtsmobile.getText().length()>0)
        {
            
            JOptionPane.showMessageDialog(this, "Enter correct MobileNo.","Error",JOptionPane.ERROR_MESSAGE);
            txtsmobile.requestFocus();
        }
    }//GEN-LAST:event_txtsmobileFocusLost



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rdocapsule;
    private javax.swing.JRadioButton rdopaste;
    private javax.swing.JRadioButton rdosyrup;
    private javax.swing.JRadioButton rdotablet;
    private javax.swing.JTextField txtbox;
    private javax.swing.JTextField txtcompany;
    private javax.swing.JTextField txtcost;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtdeadline;
    private javax.swing.JTextField txtmname;
    private javax.swing.JTextField txtmrp;
    private javax.swing.JTextField txtpkg;
    private javax.swing.JTextField txtsmobile;
    private javax.swing.JTextField txtsname;
    private javax.swing.JTextField txttablets;
    // End of variables declaration//GEN-END:variables
}
